name: real-estate

secrets:
  infisical_token:
    file: ./infisical_token.txt
  .infisical.json:
    file: ./.infisical.json

services:
  real-estate-backend:
    container_name: real-estate-backend
    build: ./backend
    image: real-estate-backend:Python-3.12-slim-D
    ports:
      - "8004:8000"
    secrets:
      - infisical_token
      - .infisical.json
    entrypoint: sh -c 
    command: ["chmod +x /app/run.sh && /app/run.sh"]
    volumes:
      - ./backend:/app
    networks:
      - web-app-network

  real-estate-backend-ai:
    container_name: real-estate-backend-ai
    build: ./backend_ai
    image: real-estate-backend-ai:Python-3.12-slim-D
    ports:
      - "8005:8001"
    secrets:
      - infisical_token
      - .infisical.json
    entrypoint: sh -c 
    command: ["chmod +x /app/run.sh && /app/run.sh"]
    volumes:
      - ./backend_ai:/app
    environment:
      - SERVICE_TYPE=ai-api
    depends_on:
      real-estate-redis:
        condition: service_healthy
      real-estate-backend:
        condition: service_started
    networks:
      - web-app-network

  real-estate-backend-ai-worker:
    container_name: real-estate-backend-ai-worker
    build: ./backend_ai
    image: real-estate-backend-ai:Python-3.12-slim-D
    secrets:
      - infisical_token
      - .infisical.json
    entrypoint: sh -c 
    command: ["chmod +x /app/run.sh && /app/run.sh"]
    volumes:
      - ./backend_ai:/app
    environment:
      - SERVICE_TYPE=ai-workers
    depends_on:
      real-estate-redis:
        condition: service_healthy
      real-estate-backend-ai:
        condition: service_started
    networks:
      - web-app-network

  real-estate-frontend:
    container_name: real-estate-frontend
    build: ./frontend
    image: real-estate-frontend:Node-20-alpine-D
    ports:
      - "3004:3000"
    secrets:
      - infisical_token
      - .infisical.json
    entrypoint: sh -c 
    command: ["chmod +x /app/run.sh && /app/run.sh"]
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    extra_hosts:
      - "real-estate.dev:host-gateway"
    networks:
      - web-app-network

  real-estate-redis:
    build: ./redis
    container_name: real-estate-redis
    image: real-estate-redis:Redis-7.4.2-alpine-D
    volumes:
      - redis-data:/data
    ports:
      - "6383:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - web-app-network

volumes:
  frontend_node_modules:
  redis-data:

networks:
  web-app-network:
    external: true